"""Add token blacklist table

Revision ID: 2a3eed298b83
Revises: be5f69bc92e9
Create Date: 2025-05-28 13:23:27.223225

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a3eed298b83'
down_revision: str | None = 'be5f69bc92e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=255), nullable=False, comment='JWT ID (unique token identifier)'),
    sa.Column('token_type', sa.String(length=20), nullable=False, comment='Type of token (access, refresh)'),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_blacklist_expires_at', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index('idx_token_blacklist_jti_type', 'token_blacklist', ['jti', 'token_type'], unique=False)
    op.create_index('idx_token_blacklist_user_revoked', 'token_blacklist', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_created_at'), 'token_blacklist', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_created_at'), table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_user_revoked', table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_jti_type', table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_expires_at', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
